# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 10:17
from __future__ import unicode_literals

from django.db import migrations
import json
from django.conf import settings
from requests import get
from django.core.files import File

def commodities_categories(apps, schema_editor):
    TradeableCategory = apps.get_model('server', 'TradeableCategory')
    with open('{0}/imports/commodities_categories.json'.format(settings.BASE_DIR)) as datafile:
        categories = json.loads(datafile.read())
        for tc in categories['categories']:
            category = TradeableCategory(name=tc['name'])
            category.icon.save(tc['icon'], File(
                open('{0}/imports/icons/{1}'.format(settings.BASE_DIR, tc['icon']),
                     'rb')), save=False)
            category.save()


def commodities(apps, schema_editor):
    Tradeable = apps.get_model('server', 'Tradeable')
    TradeableCategory = apps.get_model('server', 'TradeableCategory')

    commodities_response = get('https://eddb.io/archive/v5/commodities.json')
    commodities_list = json.loads(commodities_response.content)

    for commodity in commodities_list:
        tradeable = Tradeable(
            category=TradeableCategory.objects.get(pk=commodity['category_id']),
            name=commodity['name'],
            rare=commodity['is_rare'],
        )
        tradeable.save()

class Migration(migrations.Migration):

    SYSTEMS_JSON_FILE_URL='https://eddb.io/archive/v5/systems_populated.json'
    STATIONS_JSON_FILE_URL = 'https://eddb.io/archive/v5/stations.json'

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = []
    systems_m = {}
    db_id = 1

    # systems
    systems_response = get(SYSTEMS_JSON_FILE_URL)
    systems_populated = json.loads(systems_response.content)
    for system in systems_populated:

        systems_m[system['id']]=db_id
        db_id = db_id + 1

        operations.append(
            migrations.RunSQL(
                "INSERT INTO server_starsystem " +
                "(name, ref_eddb_system_id) VALUES " +
                "(" +
                "'" + system['name'].replace("'", "''") + "', " +
                str(system['id']) +
                ");",
                reverse_sql=''
            )
        )

    # stations
    stations_response = get(STATIONS_JSON_FILE_URL)
    stations = json.loads(stations_response.content)
    for station in stations:

        operations.append(
            migrations.RunSQL(
                "INSERT INTO server_station " +
                "(name, ref_eddb_station_id, located_in_system_id) VALUES " +
                "(" +
                "'" + station['name'].replace("'", "''") + "', " +
                str(station['id']) + ", " +
                str(systems_m[station['system_id']]) +
                ");",
                reverse_sql=''
            )
        )

    operations.append(
        migrations.RunPython(commodities_categories)
        )

    operations.append(
        migrations.RunPython(commodities)
    )