# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 21:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def activities(apps, schema_editor):
    Activity = apps.get_model('server', 'Activity')
    activities = [
        'Trading',
        'Smuggling',
        'Bounty Hunting',
        'Piracy',
        'Thargoids'
    ]

    for activity in activities:
        Activity(name=activity).save()


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_imports'),
    ]

    operations = [
        migrations.RunPython(activities),
    ]
