# Generated by Django 2.1.3 on 2018-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Is advertisement closed'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Is advertisement hidden from search and listings'),
        ),
    ]
